manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: inorichi
      url-base: https://github.com/inorichi
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: main
  self:
    path: config
